### ISSUE TITLE
Czech localization

### ISSUE THREAD

**Issue by petr-vojtech** [abjerner/Limbo.Umbraco.TextBox#1]
Hello,
can you add Czech localization to nuget package?
Thank you very much.
Petr Vojtěch

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>

<language alias="cs" intName="Czech" localName="čeština" lcid="" culture="cs-CZ">
  <area alias="limboTextBox">
    <key alias="info1"><![CDATA[Zbývá <strong class="positive">%0% znaků.]]></key>
    <key alias="info2"><![CDATA[Zbývá <strong class="negative">%0% znaků.]]></key>
    <key alias="info3"><![CDATA[Nemůžete napsat více než <strong class="negative">%0%</strong> znaků!]]></key>
  </area>
</language>
```

**Comment by abjerner** [comment]
Hi @petr-vojtech 

Yes, it should take much to add it since you've already created the file.

Can you create a PR with the file? Otherwise I'll look into adding it when I have some time 😉

**Comment by abjerner** [comment]
Closing the issue as related PR is now merged.

**Comment by petr-vojtech** [comment]
Hello,
it's great that the new version is in the Czech language.
Thanks for the build.
How should it be configured in Umbraco 10 to use Czech translations?
I still only see English messages.
Is it necessary to write something in appsettings.json ?
Thank you for your help.

**Comment by abjerner** [comment]
Hi @petr-vojtech 

If you select **Czech (Czechia)** as the language for your user in the backoffice, it should work. It did for me when I tested your PR.

You may have to reload the page to see the new language apply though.

![image](https://user-images.githubusercontent.com/3634580/217642745-13c19bf5-03c2-4dc4-be62-da1bc3651709.png)

![image](https://user-images.githubusercontent.com/3634580/217643398-ea4a19be-ee29-4101-8c37-643560170ae3.png)

**Comment by petr-vojtech** [comment]
Hi @abjerner
Everything is alright.
Thank you.
